name = "sse-room-counter"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "CounterDO"
class_name = "CounterDO"

# まず古い DO を削除
[[migrations]]
tag = "v-clean"
delete_class = "CounterDO"

# 新規作成
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CounterDO"]