name = "hello-counter-sse-v2"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "CounterDO"
class_name = "CounterDO"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["CounterDO"]
