name = "sse-room-counter"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "CounterDO"
class_name = "CounterDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CounterDO"]
