name = "helloworld"
main = "src/index.js"
compatibility_date = "2025-09-04"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]