name = "counter-sse-time"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "CounterDO2"
class_name = "CounterDO2"

[[migrations]]
tag = "v22"
new_sqlite_classes = ["CounterDO2"]
