name = "sse-room-counter"
main = "src/index.ts"
compatibility_date = "2025-09-05"

[assets]
directory = "./public"

# Durable Object のバインディング
[[durable_objects.bindings]]
name = "CounterDO"
class_name = "CounterDO"

# マイグレーション: まず削除（存在しなくてもエラーにならない）
[[migrations]]
tag = "v-clean"
delete_classes = ["CounterDO"]

# マイグレーション: 新規作成（必ずクリーンから始められる）
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CounterDO"]